### PR TITLE
fix error when no VDX file available.

### LINKED ISSUE #185: cannot load CTX without VOIs
in current master branch:
Trying to load ctx from `pytrip/tests/res/TST003/tst003000.ctx.gz`
```
bassler@baslup:~/Projects/pytripgui$ PYTHONPATH=. python3 pytripgui/main.py 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1134, resource id: 11247093, major code: 40 (TranslateCoords), minor code: 0
bassler@baslup:~/Projects/pytripgui$ PYTHONPATH=. python3 pytripgui/main.py  -vvv
DEBUG:__main__:Setup view
DEBUG:__main__:Setup model
DEBUG:__main__:Setup controller
DEBUG:pytripgui.controller.settings_cont:New setup config parser based on /home/bassler/.pytrip/settings_pytripgui.pkl
DEBUG:pytripgui.controller.settings_cont:SettingsController.load() : loading settings from /home/bassler/.pytrip/settings_pytripgui.pkl
DEBUG:pytripgui.view.dialogs:/home/bassler/Projects/pytrip/tests/res/TST003/tst003000.hed
DEBUG:pytripgui.controller.main_cont:Open CTX /home/bassler/Projects/pytrip/tests/res/TST003/tst003000.hed
INFO:pytrip.util:Locating : /home/bassler/Projects/pytrip/tests/res/TST003/tst003000.hed as <pytrip.ctx.CtxCube object at 0x7fd959354898>
INFO:pytrip.util:Found /home/bassler/Projects/pytrip/tests/res/TST003/tst003000.hed
INFO:pytrip.util:Locating : /home/bassler/Projects/pytrip/tests/res/TST003/tst003000.hed as <pytrip.ctx.CtxCube object at 0x7fd959354898>
INFO:pytrip.cube:Reading header file/home/bassler/Projects/pytrip/tests/res/TST003/tst003000.hed
DEBUG:pytrip.cube:TRiP loaded offsets: 0.000000 0.000000 0.000000
DEBUG:pytrip.cube:self.format_str: '<h'
DEBUG:pytrip.cube:self.format_str: '<h'
DEBUG:pytrip.cube:Format string:<h
INFO:pytrip.cube:Opening file: /home/bassler/Projects/pytrip/tests/res/TST003/tst003000.ctx.gz
INFO:pytrip.cube:Cube data points : 78643200
DEBUG:pytripgui.model.plot_model:setter: slice_pos_idx: 150
DEBUG:pytripgui.model.plot_model:setter: slice_size: 300
DEBUG:pytripgui.controller.main_cont:Check for VDX
DEBUG:pytripgui.controller.main_cont:Check if 'tst003000.vdx' exists...
DEBUG:pytripgui.controller.tree_cont:update_tree()
Traceback (most recent call last):
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/main_cont.py", line 165, in open_voxelplan_dialog
    self.open_voxelplan(path)
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/main_cont.py", line 221, in open_voxelplan
    self.tree.update_tree()
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/tree_cont.py", line 122, in update_tree
    self._model_sync_remove_items()
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/tree_cont.py", line 252, in _model_sync_remove_items
    lo = self._flat_model()
  File "/home/bassler/Projects/pytripgui/pytripgui/controller/tree_cont.py", line 284, in _flat_model
    if model.vdx.vois:
AttributeError: 'NoneType' object has no attribute 'vois'
Aborted
```

### PR DESCRIPTION
**Pull request by nbassler**
fix #185

### CODE REVIEW

**Comment by grzanka** [comment]
Tests are failing for same reason as in https://github.com/pytrip/pytripgui/pull/184
See relevant commits which fix issues for Travis, fixing Appveyor seems more complicated.
